name: Test Go

on:
  - push
  - pull_request

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Run Go tests
        run: go test ./...
